export const GET_PRODUCTS="GET_PRODUCTS"
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"
export const SET_CURRENT_PAGE="SET_CURRENT_PAGE"
export const SET_SELECTED_PRODUCT="SET_SELECTED_PRODUCT"
//cart Actions
export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
export const UPDATE_QUANTITY="UPDATE_QUANTITY"
//auth actionTypes
export const DO_LOGIN="DO_LOGIN"
export const DO_LOGIN_SUCCESS="DO_LOGIN_SUCCESS"
